from vector3 import *

ROT_ANGLE = 30
VELOCITY = 1
SPEED_PLAYER = 5

MIN_CUBES = 10
MAX_CUBES = 30
RANDOM_CUBES = MAX_CUBES - MIN_CUBES
RANDOM_SCALE = 5
RANDOM_POSITION = 30

Y_AXIS = vector3(0, 1, 0)
Z_AXIS = vector3(0, 0, 1)
X_AXIS = vector3(1, 0, 0)